spring:
  profiles:
    active: local

  config:
    import:
      - classpath:logback.yml

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false

server:
  servlet:
    session:
      cookie:
        same-site: strict
        http-only: true
        secure: true
    encoding:
      charset: UTF-8
      force: true

cors:
  allowed-origins:
    - http://localhost
    - https://localhost

redis:
  host: localhost
  port: 6379